# General Commands
alias sudo='sudo '
alias rm='rm -i'
alias mv='mv -i'
alias l='ls -lAhHF --group-directories-first --color=auto'
alias ll='ls -lhHF --group-directories-first --color=auto'
alias lles='ls -lAhHF --group-directories-first --color=auto | less -r'
alias llles='ls -lhHF --group-directories-first --color=auto | less -r'
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias die='shutdown now'
alias grep='grep --color=auto'
alias md='mkdir -pv'
alias mnt='mount | column -t'
alias meminfo='free -h -l -t'
alias psfind='ps -ef | grep --color=auto '
alias bsrc='source ~/.bashrc'
alias udate='date -u +"%Y-%m-%dT%H:%M:%SZ"'
alias utime='date -u +"%T"'
alias ldate='date +"%Y-%m-%dT%H:%M:%SZ"'
alias ltime='date +"%T"'
alias hisgrp='history|grep --color=auto'
alias chx='chmod --preserve-root 755'
alias chrw='chmod --preserve-root 644'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'
alias chown='chown --preserve-root'
alias fping='ping -c 10 -i .5'
alias tcp='ss -t4p'
alias ftcp='ss -t4p state'
alias xtcp='ss -t4p exclude'
alias udp='ss -u4p'
alias arules='iptables -vnL --line-numbers'
alias irules='iptables -L INPUT -nv --line-numbers'
alias orules='iptables -L OUTPUT -nv --line-numbers'
alias fwrules='iptables -L FORWARD -nv --line-numbers'
alias myip='curl myip.ipip.net'
alias apt-get="sudo apt-get"
alias apt-upgrade='sudo apt-get update && sudo apt-get upgrade'
alias dld='wget -bq --tries=5'
alias rlog='tail -F'
alias testapt='apt-get install -qsy'

# Commands may not installed by default
alias cp='rsync -az'
alias vi='vim'
alias vibs='vim ~/.bashrc'
alias t2='tree -L 2'
alias t3='tree -L 3'

# Deprecated
alias dtcp='netstat -tlnp'

# Tmux
alias tnew='tmux new -s '
alias tkill='tmux kill-session -t '
alias ta='(tmux has-session 2>/dev/null && tmux attach) || (tmux new-session)'
